eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.client.hostname}:${server.port}/eureka/

server:
  port: 8761

spring:
  cloud:
    config:
      enabled: false # Config server'ı devre dışı bırakma
